name: Compile example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Compile mousebuttons example
      run: make -C examples/mousebuttons/
      shell: bash

    - name: Compile shapes example
      run: make -C examples/shapes/
      shell: bash

    - name: Compile ttf example
      run: make -C examples/ttf/
      shell: bash
