name: Compile example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Compile mouse buttons example
      run: make -C examples/mousebuttons-c/
      shell: bash

    - name: Compile text example
      run: make -C examples/text-ttf-c/
      shell: bash
