name: Compile example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Compile Examples
      run: |
        mkdir build/
        make -C examples/mousebuttons/
        make -C examples/shapes/
        make -C examples/ttf/
        make -C examples/cookieclicker/ DESTDIR=../../build
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: examples-${{ runner.os }}
        path: build/
